const IMPORT_OBJECT_TYPES = {
  RESTAURANT: 'restaurant',
  BUSINESS: 'business',
  BOOK: 'book',
  PRODUCT: 'product',
  LINK: 'link',
  RECIPE: 'recipe',
};

const OBJECT_TYPES = {
  BOOK: 'book',
  BUSINESS: 'business',
  PERSON: 'person',
  RESTAURANT: 'restaurant',
  PRODUCT: 'product',
  LIST: 'list',
  MAP: 'map',
  LINK: 'link',
  RECIPE: 'recipe',
};

const DATAFINITY_IDS = 'keys';
const DATAFINITY_KEY = 'datafinityKey';

const OBJECT_IDS = {
  ASINS: 'asins',
  EAN13: 'ean13',
  EAN8: 'ean8',
  ISBN: 'isbn',
  UPCA: 'upca',
  UPCE: 'upce',
  VIN: 'vin',
  WALMART_NUM: 'walmartNum',
  WALMART: 'walmart',
  TARGET: 'target',
};

const MODEL_NUMBER = 'Item model number';

const AUTHORITY_FIELD_OPTIONS = {
  ADMINISTRATIVE: 'administrative',
  OWNERSHIP: 'ownership',
};

const OBJECT_FIELDS = {
  PRODUCT_ID: 'productId',
  AUTHORITY: 'authority',
  NAME: 'name',
  AGE_RANGE: 'ageRange',
  OPTIONS: 'options',
  PUBLICATION_DATE: 'publicationDate',
  DIMENSIONS: 'dimensions',
  WEIGHT: 'productWeight',
  LANGUAGE: 'language',
  PRINT_LENGTH: 'printLength',
  AUTHORS: 'authors',
  PUBLISHER: 'publisher',
  AVATAR: 'avatar',
  MAP: 'map',
  ADDRESS: 'address',
  EMAIL: 'email',
  TAG_CATEGORY: 'tagCategory',
  CATEGORY_ITEM: 'categoryItem',
  WORK_TIME: 'workTime',
  WEBSITE: 'website',
  COMPANY_ID: 'companyId',
  MERCHANT: 'merchant',
  MANUFACTURER: 'manufacturer',
  BRAND: 'brand',
  FEATURES: 'features',
  DEPARTMENTS: 'departments',
  GALLERY_ALBUM: 'galleryAlbum',
  GALLERY_ITEM: 'galleryItem',
  PRICE: 'price',
  DESCRIPTION: 'description',
  GROUP_ID: 'groupId',
  RATING: 'rating',
  MENU_ITEM: 'menuItem',
  TITLE: 'title',
  LINK: 'link',
  PHONE: 'phone',
  URL: 'url',
  CALORIES: 'calories',
  BUDGET: 'budget',
  COOKING_TIME: 'cookingTime',
  COST: 'cost',
  RECIPE_INGREDIENTS: 'recipeIngredients',
};

const VIRTUAL_FIELDS = {
  ADD_TO_LIST: 'addToList',
};

const FIELDS_BY_OBJECT_TYPE = {
  person: [
    OBJECT_FIELDS.NAME,
  ],
  restaurant: [
    OBJECT_FIELDS.NAME,
    OBJECT_FIELDS.AVATAR,
    OBJECT_FIELDS.ADDRESS,
    OBJECT_FIELDS.MAP,
    OBJECT_FIELDS.EMAIL,
    OBJECT_FIELDS.WORK_TIME,
    OBJECT_FIELDS.WEBSITE,
    OBJECT_FIELDS.COMPANY_ID,
    OBJECT_FIELDS.PHONE,
    OBJECT_FIELDS.LINK,
    OBJECT_FIELDS.DESCRIPTION,
    OBJECT_FIELDS.TAG_CATEGORY,

    VIRTUAL_FIELDS.ADD_TO_LIST,
  ],
  business: [
    OBJECT_FIELDS.NAME,
    OBJECT_FIELDS.AVATAR,
    OBJECT_FIELDS.ADDRESS,
    OBJECT_FIELDS.MAP,
    OBJECT_FIELDS.EMAIL,
    OBJECT_FIELDS.WORK_TIME,
    OBJECT_FIELDS.WEBSITE,
    OBJECT_FIELDS.COMPANY_ID,
    OBJECT_FIELDS.PHONE,
    OBJECT_FIELDS.LINK,
    OBJECT_FIELDS.DESCRIPTION,
    OBJECT_FIELDS.TAG_CATEGORY,

    VIRTUAL_FIELDS.ADD_TO_LIST,
  ],
  book: [
    OBJECT_FIELDS.NAME,
    OBJECT_FIELDS.AVATAR,
    OBJECT_FIELDS.OPTIONS,
    OBJECT_FIELDS.PRODUCT_ID,
    OBJECT_FIELDS.GROUP_ID,
    OBJECT_FIELDS.AGE_RANGE,
    OBJECT_FIELDS.PUBLICATION_DATE,
    OBJECT_FIELDS.DIMENSIONS,
    OBJECT_FIELDS.LANGUAGE,
    OBJECT_FIELDS.PRINT_LENGTH,
    OBJECT_FIELDS.PUBLISHER,
    OBJECT_FIELDS.AUTHORS,
    OBJECT_FIELDS.DEPARTMENTS,
    OBJECT_FIELDS.WEIGHT,
    OBJECT_FIELDS.PRICE,
    OBJECT_FIELDS.DESCRIPTION,
    OBJECT_FIELDS.TAG_CATEGORY,

    VIRTUAL_FIELDS.ADD_TO_LIST,
  ],
  product: [
    OBJECT_FIELDS.NAME,
    OBJECT_FIELDS.AVATAR,
    OBJECT_FIELDS.PRODUCT_ID,
    OBJECT_FIELDS.GROUP_ID,
    OBJECT_FIELDS.DIMENSIONS,
    OBJECT_FIELDS.FEATURES,
    OBJECT_FIELDS.BRAND,
    OBJECT_FIELDS.MANUFACTURER,
    OBJECT_FIELDS.MERCHANT,
    OBJECT_FIELDS.WEIGHT,
    OBJECT_FIELDS.DEPARTMENTS,
    OBJECT_FIELDS.OPTIONS,
    OBJECT_FIELDS.PRICE,
    OBJECT_FIELDS.DESCRIPTION,
    OBJECT_FIELDS.TAG_CATEGORY,

    VIRTUAL_FIELDS.ADD_TO_LIST,
  ],
  link: [
    OBJECT_FIELDS.NAME,
    OBJECT_FIELDS.AVATAR,
    OBJECT_FIELDS.URL,
    OBJECT_FIELDS.TITLE,
    OBJECT_FIELDS.DESCRIPTION,

    VIRTUAL_FIELDS.ADD_TO_LIST,
  ],
  recipe: [
    OBJECT_FIELDS.NAME,
    OBJECT_FIELDS.AVATAR,
    OBJECT_FIELDS.DESCRIPTION,
    OBJECT_FIELDS.TAG_CATEGORY,
    OBJECT_FIELDS.PRODUCT_ID,
    OBJECT_FIELDS.DEPARTMENTS,
    OBJECT_FIELDS.CALORIES,
    OBJECT_FIELDS.BUDGET,
    OBJECT_FIELDS.COOKING_TIME,
    OBJECT_FIELDS.RECIPE_INGREDIENTS,

    VIRTUAL_FIELDS.ADD_TO_LIST,
  ],
};

const FIELDS_FOR_TAGS = {
  TAG_CATEGORY: 'tagCategory',
  CATEGORY_ITEM: 'categoryItem',
};

const OBJECTS_FROM_FIELDS = {
  BUSINESS: 'business',
  PERSON: 'person',
};

const WEIGHT_UNITS = [
  't',
  'kg',
  'gm',
  'mg',
  'mcg',
  'st',
  'lb',
  'oz',
];

const DIMENSION_UNITS = [
  'km',
  'm',
  'cm',
  'mm',
  'μm',
  'mi',
  'yd',
  'ft',
  'in',
  'nmi',
];

const FIELD_LANGUAGES_TO_NLP = {
  'ru-RU': 'rus_Cyrl',
  'af-ZA': 'afr_Latn',
  'ar-SA': 'arb_Arab',
  'ca-ES': 'cat_Latn',
  'cs-CZ': 'ces_Latn',
  'da-DK': 'dan_Latn',
  'de-DE': 'deu_Latn',
  'es-ES': 'spa_Latn',
  'et-EE': 'est_Latn',
  'fil-PH': 'eng_Latn',
  'fr-FR': 'fra_Latn',
  'hi-IN': 'hin_Deva',
  'hr-HR': 'hrv_Latn',
  'hu-HU': 'hun_Latn',
  'id-ID': 'ind_Latn',
  'it-IT': 'ita_Latn',
  'ja-JP': 'jpn_Jpan',
  'ko-KR': 'kor_Hang',
  'ms-MY': 'zsm_Latn',
  'pl-PL': 'pol_Latn',
  'pt-BR': 'por_Latn',
  'uk-UA': 'ukr_Cyrl',
  'en-US': 'eng_Latn',
  'zh-CN': 'zho_Hans',
  default: 'eng_Latn',
};

const FEATURES_FILTER = [
  'Product Features',
  'Parent ASIN',
  'Best Sellers Rank',
  'Leaf Node Category',
  'Parent Node Category',
  'Parent Node Id',
  'Date First Available',
  'Leaf Node Id',
  'Hierarchy',
  'Color',
  'Item Dimensions LxWxH',
  'Packaged Quantity',
  'Style Name',
  'Body Color',
  'Key Points',
  '3G UMTS Band',
  'Product Type',
  'Additional Features',
  'Header / Brand',
  'Service Provider',
  'Root Node Id',
  'UNSPSC Code',
  'ManufacturerNumber',
  'Package Dimensions',
  'Newer model URL',
  'Department',
  'Date First Available',
  'ASIN ‏',
  'Title',
  'body html',
  'Brand',
  'Flavor',
  'Size',
  'Manufacturing Brand',
  'Tags',
  'Our Values',
  'Overall Rating',
  'Overall Rating Count',
  'Rating (Quality)',
  'Rating (Fit)',
  'Average Overall Rating',
];

const FEATURES_KEYS = {
  PARENT_ASIN: 'Parent ASIN',
  ASIN_PLUS: 'ASIN ‏',
  PRODUCT_FEATURES: 'Product Features',
  AUTHORS: 'Author',
};

const PARENT_ASIN_FIELDS = [
  FEATURES_KEYS.PARENT_ASIN,
  FEATURES_KEYS.ASIN_PLUS,
];

const CURRENCY_PREFIX = {
  AUD: 'A$',
  USD: '$',
  CAD: 'C$',
  JPY: '¥',
  NZD: 'NZ$',
  EUR: '€',
  GBP: '£',
  SGD: 'S$',
  HKD: 'HK$',
  MXN: 'MX$',
  RUB: '₽',
  CNY: '¥',
  UAH: '₴',
  CHF: '₣',
  default: '$',
};

const SIZE_POSITION = {
  'extra extra small': 10,
  xxs: 10,
  'extra small': 20,
  xs: 20,
  small: 30,
  s: 30,
  medium: 40,
  m: 40,
  large: 50,
  l: 50,
  'extra large': 60,
  xl: 60,
  'extra extra large': 70,
  xxl: 70,
  'extra extra extra large': 80,
  xxxl: 80,
  default: 0,
};

const DOMAINS = {
  AMAZON: 'www.amazon.com',
  TARGET: 'www.target.com',
  WALMART: 'www.walmart.com',
};

const ARRAY_FIELDS = [
  'categoryItem',
  'listItem',
  'tagCategory',
  'galleryItem',
  'galleryAlbum',
  'rating',
  'button',
  'phone',
  'blog',
  'form',
  'newsFilter',
  'companyId',
  'productId',
  'options',
  'authors',
  'departments',
  'features',
  'authority',
  'groupId',
  'pin',
  'remove',
  'menuItem',
  'related',
  'addOn',
  'similar',
  'affiliateGeoArea',
  'affiliateProductIdTypes',
];

const ARRAY_FIELDS_BODY = ['remove', 'groupId', 'affiliateGeoArea', 'affiliateProductIdTypes'];

const FIELDS_TO_REWRITE_GPT = [
  OBJECT_FIELDS.TITLE,
  OBJECT_FIELDS.DESCRIPTION,
];

module.exports = {
  FIELDS_TO_REWRITE_GPT,
  ARRAY_FIELDS_BODY,
  OBJECT_FIELDS,
  ARRAY_FIELDS,
  DOMAINS,
  SIZE_POSITION,
  CURRENCY_PREFIX,
  PARENT_ASIN_FIELDS,
  FEATURES_KEYS,
  FEATURES_FILTER,
  FIELD_LANGUAGES_TO_NLP,
  DIMENSION_UNITS,
  WEIGHT_UNITS,
  OBJECTS_FROM_FIELDS,
  FIELDS_FOR_TAGS,
  FIELDS_BY_OBJECT_TYPE,
  AUTHORITY_FIELD_OPTIONS,
  MODEL_NUMBER,
  OBJECT_IDS,
  DATAFINITY_KEY,
  DATAFINITY_IDS,
  OBJECT_TYPES,
  IMPORT_OBJECT_TYPES,
  VIRTUAL_FIELDS,
};
