exports.WHITE_LIST = [
  'flowmaster',
  'wiv01',
  'campingchecklist',
  'reviews.editor',
  'beatthebust',
  'cleangirl',
  'versentry',
  'sebclem',
  'antoniokevin',
  'ahmed365',
  'thapelo05',
  'davep96',
  'campzone',
  'dataoperator',
  'dataoperator2',
  'ogarces',
  'glasscity',
  'gadgetcentral',
  'techcity',
  'thestandard',
  'kingofreviews',
  'coffee.time',
  'fitness.gifts',
  'coffeegifts',
  'gmamba13',
  'waivio.affiliate',
  'cryptodive',
  'organicvibes',
  'rusn',
  'picmylife',
  'misslasvegas',
  'purewellness',
  'talismaan',
  'seanglife',
  'campinghive',
  'catshive',
];

exports.WHITE_LIST_KEY = 'white_list_import';

exports.VOTE_COST = {
  INITIAL: 0.0012,
  INITIAL_FOR_WHITE_LIST: 0.00012,
  USUAL: 0.001,
  FOR_WHITE_LIST: 0.0001,
};
