module.exports = {
  models: {
    DatafinityObject: require('./schemas/DatafinityObjectSchema'),
    ImportStatus: require('./schemas/ImportStatusSchema'),
    AuthorityStatus: require('./schemas/AuthorityStatusSchema'),
    AuthorityObject: require('./schemas/AuthorityObjectSchema'),
    DepartmentsStatus: require('./schemas/DepartmentsStatusSchema'),
    DepartmentsObject: require('./schemas/DepartmentsObjectSchema'),
    DuplicateListObject: require('./schemas/DuplicateListObjectSchema'),
    DuplicateListStatus: require('./schemas/DuplicateListStatusSchema'),
    DescriptionStatus: require('./schemas/DescriptionStatusScema'),
    DescriptionObject: require('./schemas/DescriptionObjectSchema'),
    TelegramImportUsage: require('./schemas/TelegramImportUsageSchema'),
    TagsStatus: require('./schemas/TagsStatusSchema'),
    TagsObject: require('./schemas/TagsObjectSchema'),
    RecipeGenerationStatus: require('./schemas/RecipeGenerationStatusSchema'),
    RecipeGenerated: require('./schemas/RecipeGeneratedSchema'),
    ThreadStatus: require('./schemas/ThreadStatusSchema'),
    ThreadMessage: require('./schemas/ThreadMessageSchema'),
    PostsStatus: require('./schemas/PostsStatusSchema'),
    PostImport: require('./schemas/PostImportSchema'),
    ShopifySync: require('./schemas/ShopifySyncShema'),
  },
};
