module.exports = {
  Wobj: require('./waivioDb/wObjectModel'),
  ObjectType: require('./waivioDb/ObjectTypeModel'),
  DepartmentModel: require('./waivioDb/DepartmentModel'),
  GuestManaModel: require('./waivioDb/GuestManaModel'),
  ServiceBotModel: require('./waivioDb/ServiceBotModel'),
  App: require('./waivioDb/AppModel'),
  DatafinityObject: require('./importDb/DatafinityObjectModel'),
  ImportStatusModel: require('./importDb/ImportStatusModel'),
  AuthorityStatusModel: require('./importDb/AuthorityStatusModel'),
  AuthorityObjectModel: require('./importDb/AuthorityObjectModel'),
  DepartmentsStatusModel: require('./importDb/DepartmentsStatusModel'),
  DepartmentsObjectModel: require('./importDb/DepartmentsObjectModel'),
  DuplicateListStatusModel: require('./importDb/DuplicateListStatusModel'),
  DuplicateListObjectModel: require('./importDb/DuplicateListObjectModel'),
  DescriptionObjectModel: require('./importDb/DescriptionObjectModel'),
  DescriptionStatusModel: require('./importDb/DescriptionStatusModel'),
  TelegramImportUsageModel: require('./importDb/TelegramImportUsageModel'),
  TagsStatusModel: require('./importDb/TagsStatusModel'),
  TagsObjectModel: require('./importDb/TagsObjectModel'),
  RecipeGeneratedModel: require('./importDb/RecipeGeneratedModel'),
  RecipeGenerationStatusModel: require('./importDb/RecipeGenerationStatusModel'),
  ThreadStatusModel: require('./importDb/ThreadStatusModel'),
  ThreadMessageModel: require('./importDb/ThreadMessageModel'),
  PostImportModel: require('./importDb/PostImportModel'),
  PostStatusModel: require('./importDb/PostStatusModel'),
};
